version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      - checkout

      # Upgrade pip
      - run:
          name: Upgrade pip
          command: |
            python -m pip install --upgrade pip

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover tests

workflows:
  version: 2
  build:
    jobs:
      - build
